# Generated by Django 5.2.8 on 2025-11-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للتواصل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('about', models.TextField(blank=True, null=True, verbose_name='عن المتجر')),
            ],
            options={
                'verbose_name': 'إعداد المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
