# Generated by Django 5.2.8 on 2025-11-12 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/demo/image/upload/v1699999999/default.jpg', max_length=255, null=True, verbose_name='صورة المنتج'),
        ),
    ]
